### ISSUE TITLE
Playback of protected content is not enabled

### ISSUE THREAD

**Issue by DavidOrtmann** [Sordit/TimoBox#1]
Is there anything I can do to enable DRM playback ("Playback of protected content is not enabled" when loading open.spotify.com) on my stock Chromium browser on Raspberry Pi so I can use your tool?

**Comment by Sordit** [comment]
Ohh yes sorry. I forgot to add this to the readme.

You need

sudo apt-get update
sudo apt-get install libwidevinecdm0
