### ISSUE TITLE
How do you correctly add the NFC tags?

### ISSUE THREAD

**Issue by ltctceplrm** [Sordit/TimoBox#2]
Hello, I've installed up your program on a raspberry pi running raspbian and also configured a NFC PN532 hat, and also added the extension. But when I go to the Timobox URL I cannot find how to correctly set up the NFC cards, I cannot get Timobox to skip the song or even press play.

I've tried the following formats:

- 01234567
- 01:23:45:67
- 01-23-45-67
- 01 23 45 67
- 01_23_45_67

But they seem to never get scanned or detected

**Comment by Sordit** [comment]
Did you went into settings an added your nfc tag there? You need to add it the same asthe reader types it.
If you place the curser on the Raspberry in a text input and scen the tag, you can see/copy the code.

You can add the tag directly on the Raspberry as well and just scan the tag when your curser is in the tag input.

**Comment by johnnyadora** [comment]
Thank you for the reply, I'm sorry for my late reply. Yes I did try that and it didn't work, I even just tried it again and it still doesn't seem to do anything that's why I wanted to know if I had to format them differently. I'm using a Waveshare PN532 NFC hat that's configured to use I2C, I don't know if that could be a different set-up than yours?

I think I'm probably going to end up trying to use a python script that checks for NFC tags and then trigger a Home Assistant webhook to play spotify instead since I already use Home Assistant as well.

**Comment by ltctceplrm** [comment]
Thank you for the reply, I'm sorry for my late reply. Yes I did try that and it didn't work, I even just tried it again and it still doesn't seem to do anything that's why I wanted to know if I had to format them differently. I'm using a Waveshare PN532 NFC hat that's configured to use I2C, I don't know if that could be a different set-up than yours?

I think I'm probably going to end up trying to use a python script that checks for NFC tags and then trigger a Home Assistant webhook to play spotify instead since I already use Home Assistant as well.
(Posted a second time because I used the wrong account)

**Comment by Sordit** [comment]
For the current impl to work, it is important that your reader works like a keyboard: If you scan a Tag, it needs to TYPE the id and press ENTER. If you open a textfile and scan a tag it needs to TYPE the if there. 

I use this one for example:
https://www.amazon.de/Neuftech-Reader-Kartenleseger%C3%A4t-Kartenleser-Kontaktlos/dp/B018OYOR3E/ref=mp_s_a_1_3?crid=B1UGVBQJZFQ9&keywords=rfid+reader&qid=1688619030&sprefix=rfid+re%2Caps%2C204&sr=8-3

**Comment by Sordit** [comment]
Btw you can check if your setup works, by creating a tag with e.g. "12345" and in the Browser with spotify open type "12345" ENTER.

It should load your action. You can check backend output as well and open DevTools in the browser with F12 to see more info. Or even loock at the extension log.

**Comment by ltctceplrm** [comment]
> For the current impl to work, it is important that your reader works like a keyboard: If you scan a Tag, it needs to TYPE the id and press ENTER. If you open a textfile and scan a tag it needs to TYPE the if there.

Ooh okay yeah mine doesn't work like a keyboard so that explains why it didn't work, I thought all NFC readers worked the same so any one would be good enough. Unfortunately I can't return the one I already bought so I will have to look at another solution. I'm grateful for your help and at least this way we know it was almost certainly the tag reader.

I'll close the issue since the problem wasn't your software.

**Comment by Sordit** [comment]
Thank you a lot for your feedback. I will make that clearer in the guide.
